////////////////////////////////////////////////////
// This file was generated by the tool GrayScaler.
// Source bitmap: R:\Project\GrayScaler\Icons\Stop.bmp
//
// ICON_GRAY - 2 bpp (Bit per Pixel)
// sizeof (iconStop.data) == 52
//
////////////////////////////////////////////////////
#include "icon.h"

#ifndef ICON_INFO
#define ICON_INFO(i) i,
#endif


const ICON iconStop =
{
   /* width   = */ 13,
   /* height  = */ 13,
   /* info    = */ ICON_INFO (ICON_GRAY)
   /* data [] = */
   {
      // Bit 0 is the upper most pixel
      // of the page, which is 8 pixel high
      //--- Page 0 ---
      0xfc, 0xfa,
      0x06, 0x03,
      0x03, 0x00,
      0x01, 0x01,
      0xf1, 0xf1,
      0xf1, 0xf1,
      0xf1, 0xf1,
      0xf1, 0xf1,
      0xf1, 0xf1,
      0x01, 0x01,
      0x03, 0x00,
      0x06, 0x03,
      0xfc, 0xfa,
      //--- Page 1 ---
      0x07, 0x0b,
      0x0c, 0x18,
      0x18, 0x00,
      0x10, 0x10,
      0x11, 0x11,
      0x11, 0x11,
      0x11, 0x11,
      0x11, 0x11,
      0x11, 0x11,
      0x10, 0x10,
      0x10, 0x00,
      0x08, 0x18,
      0x07, 0x0b
   }
};


